# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
default: &default
  #fb_app_id: <%= Figaro.env.fb_app_id! %>
  #fb_app_secret: <%= Figaro.env.fb_app_secret! %>

development:
  <<: *default
  secret_key_base: 1f64b3d77adf9a22d9aacb73be5301258c27399946a3c4791e5cf07394bd5019c1d07dfcc92995695602522024f85f010a4310b96717b18428504cccd94da4d3

test:
  <<: *default
  secret_key_base: 419164a22c0ba017c1332acd0d470af85bdcbc064c185e9ef155f1f9b3520ee022ff3ba657d2436b951e58deca590a588632694df8c27edaceadc5c4bbe59787

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
